name: Track Submission Progress
on:
  push:
    branches: [main]
    paths:
      - 'Data Structures & Algorithms/**/submission-*.py'

jobs:
  track-progress:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # full history so we can diff against the previous commit

      - name: Get changed submission files
        id: changed
        run: |
          FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- 'Data Structures & Algorithms/**/submission-*.py')
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Check secret exists
        run: |
          if [ -z "${{ secrets.PROJECT_TOKEN }}" ]; then
            echo "❌ PROJECT_TOKEN is empty or missing"
          else
            echo "✅ PROJECT_TOKEN is set"
          fi

      - name: Update issue per problem
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PROJECT_TOKEN }}
          script: |
                 const result = await github.graphql(
                    `query($login: String!) {
                      user(login: $login) {
                        projectsV2(first: 20) {
                          nodes { id number title }
                        }
                      }
                    }`,
                    { login: "sabari-qwerty" }
                  );
                  console.log(result.user.projectsV2.nodes);

                  
